# Site settings
title: tmi.js - docs
email: Schmoopiie@tmijs.org
description: "Twitch is a trademark or registered trademark of Twitch Interactive, Inc. in the U.S. and/or other countries. \"tmi.js\" is not operated by, sponsored by, or affiliated with Twitch Interactive, Inc. in any way."
baseurl: ""
url: "https://docs.tmijs.org"
twitter_username: Schmoopiie
github_username:  tmi.js
logo: "https://i.imgur.com/r1N7y1c.png"
permalink: :categories/:title.html
latest_version: v1.4.1
hidden_versions:
    - v1.0.0-rc1
    - v1.0.0-rc2
twitter:
    username: Schmoopiie
    image: "https://i.imgur.com/r1N7y1c.png"

# Build settings
kramdown:
    input: GFM

sass:
    sass_dir: _sass
    style: compressed

gems:
    - jekyll-seo-tag
